### ISSUE TITLE
i do not understand

### ISSUE THREAD

**Issue by zhangchier** [twolfson/gulp.spritesmith#129]
"C:\Program Files (x86)\JetBrains\WebStorm 2016.1.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\projects\demo\node_modules\gulp\bin\gulp.js --color --gulpfile c:\projects\demo\gulpfile.js default
[16:21:52] Using gulpfile c:\projects\demo\gulpfile.js
[16:21:52] Starting 'default'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Invalid file signature
    at Parser._parseSignature (c:\projects\demo\node_modules\pngjs2\lib\parser.js:51:18)
    at ChunkStream._processRead (c:\projects\demo\node_modules\pngjs2\lib\chunkstream.js:174:13)
    at ChunkStream._process (c:\projects\demo\node_modules\pngjs2\lib\chunkstream.js:193:14)
    at ChunkStream.write (c:\projects\demo\node_modules\pngjs2\lib\chunkstream.js:61:8)
    at ChunkStream.end (c:\projects\demo\node_modules\pngjs2\lib\chunkstream.js:74:10)
    at PNG.end (c:\projects\demo\node_modules\pngjs2\lib\png.js:97:16)
    at PNG.parse (c:\projects\demo\node_modules\pngjs2\lib\png.js:87:8)
    at handlePNG (c:\projects\demo\node_modules\get-pixels\node-pixels.js:17:7)
    at doParse (c:\projects\demo\node_modules\get-pixels\node-pixels.js:104:7)
    at getPixels (c:\projects\demo\node_modules\get-pixels\node-pixels.js:134:5)

**Comment by twolfson** [comment]
This error likely means a non-PNG image is using the `.png` extension, please double check that all of your source images are using the proper extension

**Comment by twolfson** [comment]
Also, sorry for the slow reply -- I was on an off-the-grid vacation
