### ISSUE TITLE
fails to read jpg

### ISSUE THREAD

**Issue by tcurdt** [twolfson/gulp.spritesmith#27]
This

    gulp.src('assets/img/**/*.jpg')
      .pipe(spritesmith({
        imgName: 'sprite.jpg',
        cssName: 'sprite.css'
      }))
      .pipe(gulp.dest(site.build + '/assets/img'));

results in

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    TypeError: Cannot read property '0' of undefined
      at quantizeAndInverse (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/jpeg-js/lib/decoder.js:353:26)
      at buildComponentData (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/jpeg-js/lib/decoder.js:506:9)
      at Object.parse (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/jpeg-js/lib/decoder.js:769:18)
      at Object.decode (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node_modules/jpeg-js/lib/decoder.js:963:11)
      at handleJPEG (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:31:21)
      at doParse (.../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:107:7)
      at .../src/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/pixelsmith/node_modules/get-pixels/node-pixels.js:175:7
      at fs.js:272:14
      at Object.oncomplete (fs.js:108:15)

**Comment by twolfson** [comment]
This is an issue inside of `jpeg-js` (underlying module that handles JPEG's). Can you upload a version of the JPEG that is giving you trouble so we can triage and open an appropriate issue in the repo?

**Comment by tcurdt** [comment]
`get-pixels` (3.1.0) depends on an ancient version of `jpeg-js` (0.0.3). Using the latest version (0.1.1) works fine.

**Comment by twolfson** [comment]
Ah, sweet. I will open a PR on `get-pixels` to get that updated =)

**Comment by twolfson** [comment]
The fix has been merged into `get-pixels` as a patch release. This means `pixelsmith`, `spritesmith`, `grunt-spritesmith`, and `gulp.spritesmith` will automatically pick it up. If you re-install `gulp.spritesmith`, then you should get the fixed `jpeg-js`.

```bash
npm uninstall gulp.spritesmith && npm install gulp.spritesmith
```

**Comment by tcurdt** [comment]
That was quick. Thanks!
