### ISSUE TITLE
Error during spritemap generation

### ISSUE THREAD

**Issue by thelinuxlich** [twolfson/gulp.spritesmith#5]
I'm using it like this:

```
gulp.task('sprite', function() {
    var spriteData = gulp.src(paths.src.sprites).pipe(spritesmith({
        imgName: 'sprite.png',
        cssName: 'sprite.css'
    }));
    spriteData.img.pipe(gulp.dest(paths.dist + "/css"));
    spriteData.css.pipe(gulp.dest(paths.dist + "/css"));
});
```

And here's the output:
```
/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/detector.js:23
  var last = Array.prototype.pop.apply(path);
                                 ^
TypeError: Object.isSealed called on non-object
    at Function.isSealed (native)
    at normalize (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/detector.js:23:34)
    at Object.detector.tmp (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/detector.js:43:10)
    at Object.generator.build (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/generator.js:45:27)
    at File.Base.init (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/base.js:31:28)
    at new File (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/node_modules/temporary/lib/file.js:23:8)
    at Object.createCanvas (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/gmsmith/lib/gmsmith.js:96:21)
    at generateCanvas (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/src/smith.js:124:16)
    at fn (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/async/lib/async.js:582:34)
    at Immediate._onImmediate (/home/thelinuxlich/gulp-validate/node_modules/gulp.spritesmith/node_modules/spritesmith/node_modules/async/lib/async.js:498:34)
```

**Comment by thucxuong** [comment]
I'm running into this issues while trying to generate a sass file, both SCSS and SASS.
```sh
/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line #2
    at throwError (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at checkStylesheet (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:1921:22)
    at Object.CSSPRules.stylesheet (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:365:40)
    at _getAST (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at exports.srcToCSSP (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2287:16)
    at Object.exports.srcToCSSP (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2292:16)
    at exports.parse (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/cssoapi.js:7:21)
    at Object.exports.justDoIt (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/node_modules/csso/lib/cssoapi.js:21:41)
    at Transform.stream._transform (/Users/apple/Documents/experiments/gulp/node_modules/gulp-csso/index.js:39:34)
    at Transform._read (_stream_transform.js:179:10)
```
Cannot make it work except for CSS output.

**Comment by twolfson** [comment]
@thucxuong You are having a different problem than the reported one. `gulp-csso` is attempting to minify the generated SASS/SCSS files as if they were CSS. Please fix your `src` files to only run `csso` after the SASS/SCSS has been compiled to CSS.

**Comment by thucxuong** [comment]
GREAT, Thanks @twolfson . I'll check it out and feedback to you.

**Comment by bdelaney** [comment]
I wonder if linuxlich ran into this when globbing files. I set up two spritesmith tasks in Gulp v 3.8.5 that both use gulp.src('images/**/*.png').
If I execute a task piping to spritesmith only, works fine. I get the expected png/css files.
But if I use your example of streaming 'continuing the pipeline' I throw the error that linuxlich opened this issue for.
`Error: Please check the validity of the CSS block starting from the line #140`
That same task was working fine using the separate streams. It only began to error when I changed my gulp.src to the glob expression.
The errors all appear to be in gulp-csso.

**Comment by twolfson** [comment]
@bdelaney I believe you are referring to thucxuong's problem not thelinuxlich's. In that case, CSSO was complaining because it wasn't minifying CSS but SASS/SCSS instead.

If you are experiencing the same problem as thucxuong, please open another issue with a code example. I didn't ask thucxuong to because it was clear solution. However, thucxuong's problem is separate with different symptoms than the thelinuxlich's problem.

**Comment by bdelaney** [comment]
Okay, I will open new issue.

**Comment by twolfson** [comment]
This has been open for a year with only @thelinuxlich's initial issue being unresolved due to no responses from them. Closing this issue.
