### ISSUE TITLE
Can't create retina sprite

### ISSUE THREAD

**Issue by gmclelland** [twolfson/gulp.spritesmith#64]
Hello,
I'm trying to create a retina sprite with this gulp task:
```
gulp.task('sprite-retina', function () {
  var data = gulp.src('src/sprite-bitmap/*.png').pipe(plugins.spritesmith({
    retinaSrcFilter: '*@2x.png',
    imgName: 'sprite-bitmap.png',
    retinaImgName: 'sprite-bitmap@2x.png',
    cssName: '_sprite-bitmap.scss'
  }));
  var imgStream = data.img.pipe(gulp.dest(paths.bitmapsprite.dest));
  var cssStream = data.css.pipe(gulp.dest(paths.bitmapsprite.dest));
  // return merge(imgStream, cssStream);
});
```
When I run the task, it gives me this error:
```
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Retina settings detected but 0 retina images were found. We have 6 normal images and expect these numbers to line up. Please double check `retinaSrcFilter`.
    at DestroyableTransform.onEnd [as _flush] (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp.spritesmith/lib/gulp-spritesmith.js:153:7)
    at DestroyableTransform.<anonymous> (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp.spritesmith/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at finishMaybe (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp.spritesmith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp.spritesmith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp.spritesmith/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DestroyableTransform.onend (/Users/glenn/websites/_visit.com/public_html/visit/sites/all/themes/visit/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
```

I have copied these images from this repo into my folders:
fork.png
fork@2x.png
github.png
github@2x.png
twitter.png
twitter@2x.png

If I comment out these lines a non retina sprite is produced with the six images:
```
 retinaSrcFilter: '*@2x.png',
 retinaImgName: 'sprite-bitmap@2x.png',
```

Any idea as to what is going on?  I'm running gulp.spritesmith 4.1.0, npm 2.14.1, and node v0.12.7

**Comment by gmclelland** [comment]
FYI...I just tried again with the latest version of node 4.1.0 and still the same error.

**Comment by twolfson** [comment]
The `retinaSrcFilter` isn't properly aligned with the filepaths to the source images. It should be a glob pattern which is consistent with the one used for `gulp.src`. The following configuration should resolve the issue:

```js
gulp.task('sprite-retina', function () {
  var data = gulp.src('src/sprite-bitmap/*.png').pipe(plugins.spritesmith({
    retinaSrcFilter: 'src/sprite-bitmap/*@2x.png',
    imgName: 'sprite-bitmap.png',
    retinaImgName: 'sprite-bitmap@2x.png',
    cssName: '_sprite-bitmap.scss'
  }));
  var imgStream = data.img.pipe(gulp.dest(paths.bitmapsprite.dest));
  var cssStream = data.css.pipe(gulp.dest(paths.bitmapsprite.dest));
  // return merge(imgStream, cssStream);
});
```

**Comment by gmclelland** [comment]
That worked, thank you so much!  It's 1:45am here and I've been trying to figure that out for a long time.

**Comment by SnisarOnline** [comment]
`
gulp.task('t_sprite', function () {
  var spriteData = gulp.src(imgDir+'*.png')
    .pipe(spritesmith({
      retinaSrcFilter: [imgDir+'*@2x.png'],
      imgName: 'sprite.png',
      retinaImgName: 'sprite@2x.png',
      cssName: 'sprite.styl'
    }));
  return spriteData.pipe(gulp.dest(Sprite_Styl));
});
`
When I run the task, it gives me this error:
`
[01:54:06] 't_sprite' errored after 37 ms
[01:54:06] Error: Retina settings detected but 17 retina images were found. We have 0 normal images and expect these numbers to line up. Please double check `retinaSrcFilter`.
    at DestroyableTransform.onEnd [as _flush] (/var/www/node_modules/gulp.spritesmith/lib/gulp-spritesmith.js:145:19)
    at DestroyableTransform.<anonymous> (/var/www/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/var/www/node_modules/readable-stream/lib/_stream_writable.js:503:12)
    at finishMaybe (/var/www/node_modules/readable-stream/lib/_stream_writable.js:511:7)
    at endWritable (/var/www/node_modules/readable-stream/lib/_stream_writable.js:523:3)
    at DestroyableTransform.Writable.end (/var/www/node_modules/readable-stream/lib/_stream_writable.js:493:41)
    at DestroyableTransform.onend (/var/www/node_modules/readable-stream/lib/_stream_readable.js:504:10)
`

**Comment by SnisarOnline** [comment]
> 
gulp.task('t_sprite', function () {
  var spriteData = gulp.src(imgDir+'*.png')
    .pipe(spritesmith({
      retinaSrcFilter: [imgDir+'*@2x.png'],
      imgName: 'sprite.png',
      retinaImgName: 'sprite@2x.png',
      cssName: 'sprite.styl'
    }));
  return spriteData.pipe(gulp.dest(Sprite_Styl));
});
>

**Comment by SnisarOnline** [comment]
I'm trying to create a retina sprite with this gulp task:

> ```
> gulp.task('t_sprite', function () {
>   var spriteData = gulp.src(imgDir+'*.png')
>   .pipe(debug({title:"png : "}))
>     .pipe(spritesmith({
>       retinaSrcFilter: [imgDir+'*@2x.png'],
>       imgName: 'sprite.png',
>       retinaImgName: 'sprite@2x.png',
>       cssName: 'sprite.styl'
>     }));
>   return spriteData.pipe(gulp.dest(Sprite_Styl));
> });
> ```

When I run the task, it gives me this error:

> 
> ```
> [02:09:16] "t_sprite" errored after 37 ms
> [02:09:16] Error: Retina settings detected but 0 retina images were found. We have 17 normal images and expect these numbers to line up. Please double check "retinaSrcFilter".
>     at DestroyableTransform.onEnd [as _flush] (/var/www/node_modules/gulp.spritesmith/lib/gulp-spritesmith.js:145:19)
>     at DestroyableTransform.<anonymous> (/var/www/node_modules/readable-stream/lib/_stream_transform.js:115:49)
>     at DestroyableTransform.g (events.js:291:16)
>     at emitNone (events.js:86:13)
>     at DestroyableTransform.emit (events.js:185:7)
>     at prefinish (/var/www/node_modules/readable-stream/lib/_stream_writable.js:503:12)
>     at finishMaybe (/var/www/node_modules/readable-stream/lib/_stream_writable.js:511:7)
>     at endWritable (/var/www/node_modules/readable-stream/lib/_stream_writable.js:523:3)
>     at DestroyableTransform.Writable.end (/var/www/node_modules/readable-stream/lib/_stream_writable.js:493:41)
>     at DestroyableTransform.onend (/var/www/node_modules/readable-stream/lib/_stream_readable.js:504:10)
> 
> Process finished with exit code 1
> ```
