### ISSUE TITLE
error: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by FlTr** [twolfson/gulp.spritesmith#75]
Used grunt-spritesmith bevore and now migrating to gulp. But i'm getting an error and i don't know why. Can somebody help?

Here the relevant part of my gulpfile:
```js
var gulp = require( "gulp" ),
	$ = require( "gulp-load-plugins" )();
var log = $.util.log,
	rgb = $.util.colors;
	
var cfg = {
	spritesmith: {
		imgName: "spritesheet.png",
		cssName: "sprites.scss"
	}
};

gulp.task( "sprite", function() {
	return gulp
		.src( "img/*.png" )
		.pipe( $.debug())
		.pipe( $.spritesmith( cfg.spritesmith ))
		//.pipe( $.imagemin())
		.pipe( gulp.dest( "css/" ));
});
```

And here the error trace:
```
>> gulp sprite
[21:06:56] Using gulpfile ~\...\themes\gulpfile.js
[21:06:56] Starting 'sprite'...
[21:06:57] gulp-debug: img\css3.png
[21:06:57] gulp-debug: img\html5.png
[21:06:57] gulp-debug: 2 items
C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\json2css\lib\json2css.js:81
      var escapedImg = img.replace(/['"\(\)\s]/g, function encodeCssUri (chr) {
                          ^

TypeError: Cannot read property 'replace' of undefined
    at C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\json2css\lib\json2css.js:81:27
    at Array.forEach (native)
    at Object.Input.escapeImages (C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\json2css\lib\json2css.js:75:16)
    at json2css (C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\json2css\lib\json2css.js:40:12)
    at generateCss (C:\Users\...\themes\node_modules\gulp-spritesmith\lib\generateCss.js:39:12)
    at C:\Users\...\themes\node_modules\gulp-spritesmith\index.js:37:26
    at smithCallbackData (C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\spritesmith\src\smith.js:156:7)
    at fn (C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\async\lib\async.js:582:34)
    at Immediate._onImmediate (C:\Users\...\themes\node_modules\gulp-spritesmith\node_modules\async\lib\async.js:498:34)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by twolfson** [comment]
This package is `gulp.spritesmith`, not `gulp-spritesmith`. It looks like the wrong one is installed:

```bash
npm uninstall gulp-spritesmith
npm install gulp.spritesmith
```

**Comment by FlTr** [comment]
Shame on me ... 

It is not really usual to use a dot.
But thank you for this fast answer.

**Comment by twolfson** [comment]
We were planning on releasing as `gulp-spritesmith`. Unfortunately, they got to `npm` first (we wound up releasing the same week) and we couldn't agree on merging the repositories.

https://github.com/Otouto/gulp-spritesmith/issues/3
